c_compiler_version:             # [linux]
  - 11.2.0                      # [linux]
cxx_compiler_version:           # [linux]
  - 11.2.0                      # [linux]

MACOSX_DEPLOYMENT_TARGET:       # [osx]
  - 10.13                       # [osx]
CONDA_BUILD_SYSROOT:            # [osx]
  - /opt/MacOSX10.13.sdk        # [osx]
